name: Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/LZ4.net2
    steps:
    - uses: actions/checkout@latest
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@latest
    - name: Setup NuGet
      uses: NuGet/setup-nuget@latest
    - name: Build Solution
      run: |
        msbuild.exe LZ4.net2.csproj /nologo