name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/LZ4.net2
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: echo "Building with ${{ env.VERSION }}"
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --output nupkgs --configuration Release -p:Version=${{ env.VERSION }}
    - name: Nuget Publish
      run: dotnet nuget push nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json