name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/LZ4.net2
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
    - name: Pack
      run: nuget pack LZ4.net2.csproj -OutputDirectory nupkgs -Build -Version ${{ env.VERSION }} -Properties version="${{ env.VERSION }}"
    - name: Nuget Publish
      run: nuget push nupkgs\*.nupkg -ApiKey ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json